server:
  port: 80
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  datasource:
    druid:
      initial-size: 1
      max-active: 3
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/ccms?useUnicode=true&characterEncoding=utf8
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: true
    date-format: java.text.SimpleDateFormat

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      connect-timeout: 5000
      lettuce:
        pool:
          max-active: 8
          max-idle: 3
          min-idle: 1
          max-wait: 5000


  mail:
    host: smtp.qiye.aliyun.com
    port: 25
    username: youEmailAddress
    password: youEmailPassword
    default-encoding: UTF-8
    from: nickname<youEmailAddress>
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        debug: true


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


logging:
  level:
    root: info

# 以下是自定义配置
ccms:
  login:
    url: /account/login.do
  pos:
    default:
      password: 888888
  response:
    NO_LOGIN_JSON: "{\"success\":false,\"message\":\"未登录\"}"
    OPERATION_WITHOUT_PERMISSION_JSON: "{\"success\":false,\"message\":\"无权操作\"}"
  snowflake:
    machine-id: 0
    data-center-id: 0

  authentication:
    gitee:
      clientId: 06c9956bdfd279c5c0a81f187711cc7137f268331f701fcf53382e40e9f69cee
      clientSecret: adc73ff714c0b29d0af634c2d0f20187d089eb7fdbfc7809a26afa85932010e1
      callback:
        login: http://localhost/authentication/gitee/login.do
        bind: http://localhost/authentication/gitee/bind.do

    dingtalk:
      appKey: dingfi9mcuubqqqkgbec
      appSecret: 2EF6rPtFpWN3dgMKIqihFGknDCbE6ceGKk2RmBfpP5hTvdcsFZGz9N6uqyvItWd7
      callback:
        login: http://localhost/authentication/dingtalk/login.do
        bind: http://localhost/authentication/dingtalk/bind.do

