server:
  port: 80
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  datasource:
    druid:
      initial-size: 1
      max-active: 3
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/ccms?useUnicode=true&characterEncoding=utf8
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: true
    date-format: java.text.SimpleDateFormat

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      connect-timeout: 5000
      lettuce:
        pool:
          max-active: 8
          max-idle: 3
          min-idle: 1
          max-wait: 5000


  mail:
    host: smtp.qiye.aliyun.com
    port: 25
    username: youEmailAddress
    password: youEmailPassword
    default-encoding: UTF-8
    from: nickname<youEmailAddress>
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        debug: true


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


logging:
  level:
    root: info

# 以下是自定义配置
ccms:
  snowflake:
    machine-id: 0
    data-center-id: 0
  jwt:
    secret: 123456
    expire: 3600

#  authentication:
#    gitee:
#      id: 06c9956bdfd279c5c0a81f187711cc7137f268331f701fcf53382e40e9f69cee
#      secret: adc73ff714c0b29d0af634c2d0f20187d089eb7fdbfc7809a26afa85932010e1
#      authorize: https://gitee.com/oauth/authorize
#      accessToken: https://gitee.com/oauth/token
#      userInfo: https://gitee.com/api/v5/user
#      callback: http://localhost/auth/gitee/callback.do
#      redirect: redirect:/page/common/authentication/result.html
#
#    dingtalk:
#      id: dingfi9mcuubqqqkgbec
#      secret: 2EF6rPtFpWN3dgMKIqihFGknDCbE6ceGKk2RmBfpP5hTvdcsFZGz9N6uqyvItWd7
#      authorize: https://login.dingtalk.com/oauth2/auth
#      accessToken: https://oapi.dingtalk.com/gettoken
#      userInfo: https://oapi.dingtalk.com/sns/getuserinfo_bycode
#      callback: http://localhost/auth/dingtalk/callback.do
#      redirect: redirect:/page/common/authentication/result.html
#
#    alipay:
#      id: 2021000122602075
#      secret:
#      #authorize: https://openauth.alipay.com/oauth2/publicAppAuthorize.htm
#      authorize: https://openauth.alipaydev.com/oauth2/publicAppAuthorize.htm
#      accessToken:
#      userInfo:
#      callback: http://localhost/auth/alipay/callback.do
#      redirect: redirect:/page/common/authentication/result.html
#      #gateway: https://openapi.alipay.com/gateway.do
#      gateway: https://openapi.alipaydev.com/gateway.do
#      appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCGfGJTl9w3hLjWUNKe81FyxbLfILTQc6/s3iL5jGN9LH/RdD6LG4F9eBKfStkNzViwSrponxp1QqT/QZMk4K/czMQbhb6cloUlAA/+12RRlgJGHvC6K+pwgfA7hR6yEjBTCZjWwzRazXLCbCG5wUO2QAyn1ZOIiSZ4bzdvnMwSd3LxqnqNPj3QUEfPaHLn3CbcgRo1fkGF/JDlbPKDhoYE145L2I7srLSftQkhA3PYypBOG8vnvhM5UJnWzqZfXOWxZKkeZN3J2H0VbNeZ7MMSE023lVhaXQKbKbDcmXzWBPUfVqQ7Xk/pX7xUI2EoRN6nhJhFq84XyHTbJlta/gVNAgMBAAECggEASByICLTEE0zqY5ig5zQm9zjEydnaum9d5M/TxyWc7zCeNOx04NhV3bY1ng5fRoRWSuk2/QRbBoc+u9QolzyXb/ioKu3TIFmheQ6IhShvlUOvYnQStnD3224BJ5kgtXEFUnEx7+5ps0q4f0HF77mOmjnLz265FhwccbWI7yMPVdLILBH03Vx7i8Ryrl2azOEZMaORPEfDUg2FoQk4IuodP9s7W2e0lrjyRPx9qarO/E7y+FNo69G5g+JjavT3ZS/LPorenXAhznixZJNcVzw9FgWc6T4e2U80q2fzQCc8yK5pwyoLPusgvy3HcobV+q4DC6eq2or2KH4cVrEl8woxgQKBgQDTp/h0097q0VbqnL6tnaeMwU/FVLHKwg6cPu1X7RjnV8+GSJz8ccaO09+1lvgsxJNZtNdjvFAUUAm5NohOO/gPUaX2+pR80RZMcu+xPb0bmqRit1/KyMiFNUAJ3s7CqxTshoUln4dLdn5Z8ljY0D66AqcJACtYEPr6JgoeQw/rLQKBgQCiqXC+FOttxgrWXMK/36ZA9lyenC6O+1jhBynUahrVJUXmla5tMy6j3q5iM+G0fZfAUYW6qaEVI/NRJ2wSBuL1WNwcfY8YwHE9oQxZuMublxapVAHyIlTTsOY7G6Rbn9hJ6rH2XbnOpbJA5BKqE55VtAUtwPfgv2LuWZnEnSJWoQKBgQC/f0cFdLhInnTUOlMuw+hXKoPhFxrxRxhu92RIXEVe8ozZgxM+ODac/Ud3hYsu/gAPdtY176hIaI4TnCpBFnL+cTIGvnrgX1CchJUnOKPDuOuoQR8TWwxJsX8qLwPFD4MT6TXIb4i6lxAEk4cdS3SlWUcFlrigqmRZNVeMP8LEVQKBgC302Vma53k4Ps+ZnZxAP+SStlBJqA3VjaLmNzdAUxxtT3Z6S7GmiELcI0Czj81CvqEjZzj5u/0RDymajbn6IB1ZYbba8pb3qAbVfXvL7hqjcU+d4H7cnELC9Ak3IhSQ8LbRjD4i9OAhiF81EODkchOcrOnkXyQsbnMQ9ZTLIGyBAoGAZi7ovAyTeJ53013hO16aDXG1MoDrlaIESezgbAgp2uZ/YPYteAlqedqV/TJ9tU2I7EPWjdZWhF68a0yf4xsNqCyz1cG5JQsZ84S2jRXAR3cnWFzCbb8aKDKLyb+pgO3eX+6qIHBEgkI+CXd46BwlXGBPAmB8w5OtKhY/E658jc0=
#      alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlCo19SBLhxFwc/mEn9sRDPO9uozQBLXI06FOkGuU351d3c5XGz1YpKL5DKdvFN9Yph8gFdQ4ksV8NJFz4belGjWsV0k0cwXr0dyrnYkjxAOMaUP8C1pypp+J2cJvxtdPVUx+hXDDTFaAPEhqdg4sCScfzz6ugM2SabKOPT0nZioTpXOxsI4S/WYjYHz0885Vw8kimTx58MNs/88XLDPY9MybvpruOeWu01HbnWnRKD1UfJnSoeSNl2t6XP/fIbADENFZ8PcnYc6Cx7AxFpDss1Xnu+MK18o7WZjfxnt+1nsL4ZpG5ZPW0M6SOFKibpOXRl9dhrgZgykonk8cXWbZvQIDAQAB
