server:
  port: 80
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  datasource:
    druid:
      initial-size: 1
      max-active: 3
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/ccms?useUnicode=true&characterEncoding=utf8
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: true
    date-format: java.text.SimpleDateFormat

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

  mail:
    host: smtp.qiye.aliyun.com
    port: 25
    username: youEmailAddress
    password: youEmailPassword
    default-encoding: UTF-8
    from: nickname<youEmailAddress>
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        debug: true


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  level:
    root: info
